_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: Kdeployer
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: true
  bot_user:
    display_name: Kdeployer
    always_online: false
  slash_commands:
    - command: /kdeploy
      url: https://kdeployer.abtech.dev/environments
      description: (dev) Deploy (Kubernetes)
      usage_hint: "Deploys on kubernetes - config:
        https://github.com/appliedblockchain/kube-deployer-config"
      should_escape: false
oauth_config:
  scopes:
    bot:
      - commands
settings:
  interactivity:
    is_enabled: true
    request_url: https://kdeployer.abtech.dev/deployment
  org_deploy_enabled: false
  socket_mode_enabled: false
